integrate redux with edit page
dzianisbohush/passport_app pull request #16
Opened 2019-07-08 16:13 UTC by andrewyanushkevich

2019-07-08 21:10 UTC, Dmitriyjd requested changes

2019-07-08 21:10 UTC, Dmitriyjd commented on src/common/api/getPasswordsByUserId.js
> +    throw console.error(error);
Do we really need to have throw statement here?

2019-07-08 21:10 UTC, Dmitriyjd commented on src/common/pages/edit/components/PasswordForm/component.jsx
> +                { required: true, message: 'Please input resource address!' },
Move message into constants

2019-07-08 21:10 UTC, Dmitriyjd commented on src/common/pages/edit/containers/index.js
> +  addPasswordFailure,
1. This is editing page, not password creation page.
2. For initial action name use word `Pending`. Like we have pending in `Promises`.

2019-07-08 21:10 UTC, Dmitriyjd commented on src/common/pages/edit/containers/index.js
> +    throw e;
Do we really need to throw something?

2019-07-08 21:10 UTC, Dmitriyjd commented on src/common/pages/edit/containers/index.js
> +  undefined,
We need to use `mapStateToProps` function to get original password's params from the store.

2019-07-08 21:10 UTC, Dmitriyjd commented on src/common/store/rootReducer.js
> +const HOME_GET_PASSWORDS_BEGIN = 'HOME_GET_PASSWORDS_BEGIN';
Do no forget to rename begin to pending.

2019-07-08 21:10 UTC, Dmitriyjd commented on src/common/store/rootReducer.js
> +      return Object.assign({}, state, {
Use merging via spread operator instead. { ...state, items: [] }

2019-07-09 14:13 UTC, dzianisbohush commented
you will able to find these changes in another pull request

2019-07-09 14:13 UTC, closed without merging